"""empty message

Revision ID: ed511863458e
Revises: 79e7fb1c7c33
Create Date: 2025-12-07 10:16:53.764498

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ed511863458e"
down_revision: Union[str, Sequence[str], None] = "79e7fb1c7c33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
